### ISSUE TITLE
Update documentation for Kotlin DSL

### ISSUE THREAD

**Issue by ivakub** [android/project-replicator#36]
Hi! 

This code in build.gradle.kts doesn't work:
```
plugins {
    kotlin("jvm") version "1.7.21"
}

buildscript {
    repositories {
        repositories {
            mavenLocal()
            jcenter()
        }
        dependencies {
            classpath("com.android.gradle.replicator:project-replicator:0.2")
        }
    }
}

allprojects {
    apply(plugin = "com.android.gradle.replicator.ProjectReplicatorPlugin") // Plugin with id 'com.android.gradle.replicator.ProjectReplicatorPlugin' not found.
}
```
What should I do to make it work?

**Comment by ducrohet** [comment]
The plugin is not published anywhere. you need to build it and publish it locally first.

See [`USAGE.md`](https://github.com/android/project-replicator/blob/master/docs/USAGE.md) for instructions

**Comment by ivakub** [comment]
Yes, I published the plugin. It works with Groovy DSL.

**Comment by ducrohet** [comment]
oh the issue I think is that the `plugin` entry in the map provided to `apply` should be `Class` object not a `String`. By passing a string Gradle expects the plugin id but you pass there is the plugin class.

I think

`apply(plugin = com.android.gradle.replicator.ProjectReplicatorPlugin.class::java)`

should work

**Comment by ivakub** [comment]
`apply(plugin = "com.android.gradle.project.replicator")` works
